services:
  node-app:
    container_name: node-app
    image: pandatagroup/docker-intro:prod
    ports:
      - 3003:3000
    restart: unless-stopped

  postgres-db:
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: exampletest
    restart: unless-stopped